// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common_requests/common_requests.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct CommonRequests_DeliveryStatusPayload: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var chatID: Common_ChatId {
        get { return _chatID ?? Common_ChatId() }
        set { _chatID = newValue }
    }

    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool { return _chatID != nil }
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() { _chatID = nil }

    public var memberID: Common_ChatMemberId {
        get { return _memberID ?? Common_ChatMemberId() }
        set { _memberID = newValue }
    }

    /// Returns true if `memberID` has been explicitly set.
    public var hasMemberID: Bool { return _memberID != nil }
    /// Clears the value of `memberID`. Subsequent reads from it will return its default value.
    public mutating func clearMemberID() { _memberID = nil }

    public var trackID: Common_DeliveryTrackId {
        get { return _trackID ?? Common_DeliveryTrackId() }
        set { _trackID = newValue }
    }

    /// Returns true if `trackID` has been explicitly set.
    public var hasTrackID: Bool { return _trackID != nil }
    /// Clears the value of `trackID`. Subsequent reads from it will return its default value.
    public mutating func clearTrackID() { _trackID = nil }

    public var deliveryStatus: Common_DeliveryStatus = .unknown

    public var postID: Common_PostId {
        get { return _postID ?? Common_PostId() }
        set { _postID = newValue }
    }

    /// Returns true if `postID` has been explicitly set.
    public var hasPostID: Bool { return _postID != nil }
    /// Clears the value of `postID`. Subsequent reads from it will return its default value.
    public mutating func clearPostID() { _postID = nil }

    public var commentID: Common_CommentId {
        get { return _commentID ?? Common_CommentId() }
        set { _commentID = newValue }
    }

    /// Returns true if `commentID` has been explicitly set.
    public var hasCommentID: Bool { return _commentID != nil }
    /// Clears the value of `commentID`. Subsequent reads from it will return its default value.
    public mutating func clearCommentID() { _commentID = nil }

    public var layerID: Common_LayerId {
        get { return _layerID ?? Common_LayerId() }
        set { _layerID = newValue }
    }

    /// Returns true if `layerID` has been explicitly set.
    public var hasLayerID: Bool { return _layerID != nil }
    /// Clears the value of `layerID`. Subsequent reads from it will return its default value.
    public mutating func clearLayerID() { _layerID = nil }

    public var reactionID: Common_ReactionId {
        get { return _reactionID ?? Common_ReactionId() }
        set { _reactionID = newValue }
    }

    /// Returns true if `reactionID` has been explicitly set.
    public var hasReactionID: Bool { return _reactionID != nil }
    /// Clears the value of `reactionID`. Subsequent reads from it will return its default value.
    public mutating func clearReactionID() { _reactionID = nil }

    public var timestamp: Common_Timestamp {
        get { return _timestamp ?? Common_Timestamp() }
        set { _timestamp = newValue }
    }

    /// Returns true if `timestamp` has been explicitly set.
    public var hasTimestamp: Bool { return _timestamp != nil }
    /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
    public mutating func clearTimestamp() { _timestamp = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _chatID: Common_ChatId?
    fileprivate var _memberID: Common_ChatMemberId?
    fileprivate var _trackID: Common_DeliveryTrackId?
    fileprivate var _postID: Common_PostId?
    fileprivate var _commentID: Common_CommentId?
    fileprivate var _layerID: Common_LayerId?
    fileprivate var _reactionID: Common_ReactionId?
    fileprivate var _timestamp: Common_Timestamp?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "common_requests"

extension CommonRequests_DeliveryStatusPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".DeliveryStatusPayload"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "chat_id"),
        2: .standard(proto: "member_id"),
        3: .standard(proto: "track_id"),
        4: .standard(proto: "delivery_status"),
        5: .standard(proto: "post_id"),
        6: .standard(proto: "comment_id"),
        7: .standard(proto: "layer_id"),
        8: .standard(proto: "reaction_id"),
        9: .same(proto: "timestamp"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_chatID)
            case 2: try decoder.decodeSingularMessageField(value: &_memberID)
            case 3: try decoder.decodeSingularMessageField(value: &_trackID)
            case 4: try decoder.decodeSingularEnumField(value: &deliveryStatus)
            case 5: try decoder.decodeSingularMessageField(value: &_postID)
            case 6: try decoder.decodeSingularMessageField(value: &_commentID)
            case 7: try decoder.decodeSingularMessageField(value: &_layerID)
            case 8: try decoder.decodeSingularMessageField(value: &_reactionID)
            case 9: try decoder.decodeSingularMessageField(value: &_timestamp)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._chatID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        try { if let v = self._memberID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._trackID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        if deliveryStatus != .unknown {
            try visitor.visitSingularEnumField(value: deliveryStatus, fieldNumber: 4)
        }
        try { if let v = self._postID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
        } }()
        try { if let v = self._commentID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
        } }()
        try { if let v = self._layerID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
        } }()
        try { if let v = self._reactionID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
        } }()
        try { if let v = self._timestamp {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: CommonRequests_DeliveryStatusPayload, rhs: CommonRequests_DeliveryStatusPayload) -> Bool {
        if lhs._chatID != rhs._chatID { return false }
        if lhs._memberID != rhs._memberID { return false }
        if lhs._trackID != rhs._trackID { return false }
        if lhs.deliveryStatus != rhs.deliveryStatus { return false }
        if lhs._postID != rhs._postID { return false }
        if lhs._commentID != rhs._commentID { return false }
        if lhs._layerID != rhs._layerID { return false }
        if lhs._reactionID != rhs._reactionID { return false }
        if lhs._timestamp != rhs._timestamp { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
