// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/chat_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Entities_ChatEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var chatID: Common_ChatId {
        get { return _chatID ?? Common_ChatId() }
        set { _chatID = newValue }
    }

    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool { return _chatID != nil }
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() { _chatID = nil }

    public var chatType: Common_ChatType = .unknown

    public var title: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _chatID: Common_ChatId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_ChatEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ChatEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "chat_id"),
        2: .standard(proto: "chat_type"),
        3: .same(proto: "title"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_chatID)
            case 2: try decoder.decodeSingularEnumField(value: &chatType)
            case 3: try decoder.decodeSingularStringField(value: &title)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._chatID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if chatType != .unknown {
            try visitor.visitSingularEnumField(value: chatType, fieldNumber: 2)
        }
        if !title.isEmpty {
            try visitor.visitSingularStringField(value: title, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_ChatEntity, rhs: Entities_ChatEntity) -> Bool {
        if lhs._chatID != rhs._chatID { return false }
        if lhs.chatType != rhs.chatType { return false }
        if lhs.title != rhs.title { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
