// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/layer_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Entities_LayerEntity: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var layerID: Common_LayerId {
        get { return _storage._layerID ?? Common_LayerId() }
        set { _uniqueStorage()._layerID = newValue }
    }

    /// Returns true if `layerID` has been explicitly set.
    public var hasLayerID: Bool { return _storage._layerID != nil }
    /// Clears the value of `layerID`. Subsequent reads from it will return its default value.
    public mutating func clearLayerID() { _uniqueStorage()._layerID = nil }

    public var postID: Common_PostId {
        get { return _storage._postID ?? Common_PostId() }
        set { _uniqueStorage()._postID = newValue }
    }

    /// Returns true if `postID` has been explicitly set.
    public var hasPostID: Bool { return _storage._postID != nil }
    /// Clears the value of `postID`. Subsequent reads from it will return its default value.
    public mutating func clearPostID() { _uniqueStorage()._postID = nil }

    public var memberID: Common_ChatMemberId {
        get { return _storage._memberID ?? Common_ChatMemberId() }
        set { _uniqueStorage()._memberID = newValue }
    }

    /// Returns true if `memberID` has been explicitly set.
    public var hasMemberID: Bool { return _storage._memberID != nil }
    /// Clears the value of `memberID`. Subsequent reads from it will return its default value.
    public mutating func clearMemberID() { _uniqueStorage()._memberID = nil }

    public var layerType: Common_LayerType {
        get { return _storage._layerType }
        set { _uniqueStorage()._layerType = newValue }
    }

    public var x: Double {
        get { return _storage._x }
        set { _uniqueStorage()._x = newValue }
    }

    public var y: Double {
        get { return _storage._y }
        set { _uniqueStorage()._y = newValue }
    }

    public var scale: Double {
        get { return _storage._scale }
        set { _uniqueStorage()._scale = newValue }
    }

    public var rotation: Double {
        get { return _storage._rotation }
        set { _uniqueStorage()._rotation = newValue }
    }

    public var attribute: OneOf_Attribute? {
        get { return _storage._attribute }
        set { _uniqueStorage()._attribute = newValue }
    }

    public var textAttributes: Entities_TextAttributes {
        get {
            if case let .textAttributes(v)? = _storage._attribute { return v }
            return Entities_TextAttributes()
        }
        set { _uniqueStorage()._attribute = .textAttributes(newValue) }
    }

    public var gifAttributes: Entities_GifAttributes {
        get {
            if case let .gifAttributes(v)? = _storage._attribute { return v }
            return Entities_GifAttributes()
        }
        set { _uniqueStorage()._attribute = .gifAttributes(newValue) }
    }

    public var stickerAttributes: Entities_StickerAttributes {
        get {
            if case let .stickerAttributes(v)? = _storage._attribute { return v }
            return Entities_StickerAttributes()
        }
        set { _uniqueStorage()._attribute = .stickerAttributes(newValue) }
    }

    public var timestamp: Common_Timestamp {
        get { return _storage._timestamp ?? Common_Timestamp() }
        set { _uniqueStorage()._timestamp = newValue }
    }

    /// Returns true if `timestamp` has been explicitly set.
    public var hasTimestamp: Bool { return _storage._timestamp != nil }
    /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
    public mutating func clearTimestamp() { _uniqueStorage()._timestamp = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Attribute: Equatable, Sendable {
        case textAttributes(Entities_TextAttributes)
        case gifAttributes(Entities_GifAttributes)
        case stickerAttributes(Entities_StickerAttributes)
    }

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

/// Message for TextAttributes
public struct Entities_TextAttributes: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var fontStyle: String = .init()

    public var fontColor: String = .init()

    public var fontSize: Double = 0

    public var backgroundStyle: String = .init()

    public var backgroundColor: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

/// Message for GifAttributes
public struct Entities_GifAttributes: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var url: String = .init()

    public var width: Double = 0

    public var height: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

/// Message for StickerAttributes
public struct Entities_StickerAttributes: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var url: String = .init()

    public var width: Double = 0

    public var height: Double = 0

    public var rotation: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_LayerEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".LayerEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "layer_id"),
        2: .standard(proto: "post_id"),
        3: .standard(proto: "member_id"),
        4: .standard(proto: "layer_type"),
        5: .same(proto: "x"),
        6: .same(proto: "y"),
        7: .same(proto: "scale"),
        8: .same(proto: "rotation"),
        9: .same(proto: "textAttributes"),
        10: .same(proto: "gifAttributes"),
        11: .same(proto: "stickerAttributes"),
        12: .same(proto: "timestamp"),
    ]

    fileprivate class _StorageClass {
        var _layerID: Common_LayerId?
        var _postID: Common_PostId?
        var _memberID: Common_ChatMemberId?
        var _layerType: Common_LayerType = .unknown
        var _x: Double = 0
        var _y: Double = 0
        var _scale: Double = 0
        var _rotation: Double = 0
        var _attribute: Entities_LayerEntity.OneOf_Attribute?
        var _timestamp: Common_Timestamp?

        #if swift(>=5.10)
            // This property is used as the initial default value for new instances of the type.
            // The type itself is protecting the reference to its storage via CoW semantics.
            // This will force a copy to be made of this reference when the first mutation occurs;
            // hence, it is safe to mark this as `nonisolated(unsafe)`.
            nonisolated(unsafe) static let defaultInstance = _StorageClass()
        #else
            static let defaultInstance = _StorageClass()
        #endif

        private init() {}

        init(copying source: _StorageClass) {
            _layerID = source._layerID
            _postID = source._postID
            _memberID = source._memberID
            _layerType = source._layerType
            _x = source._x
            _y = source._y
            _scale = source._scale
            _rotation = source._rotation
            _attribute = source._attribute
            _timestamp = source._timestamp
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._layerID)
                case 2: try decoder.decodeSingularMessageField(value: &_storage._postID)
                case 3: try decoder.decodeSingularMessageField(value: &_storage._memberID)
                case 4: try decoder.decodeSingularEnumField(value: &_storage._layerType)
                case 5: try decoder.decodeSingularDoubleField(value: &_storage._x)
                case 6: try decoder.decodeSingularDoubleField(value: &_storage._y)
                case 7: try decoder.decodeSingularDoubleField(value: &_storage._scale)
                case 8: try decoder.decodeSingularDoubleField(value: &_storage._rotation)
                case 9: try {
                        var v: Entities_TextAttributes?
                        var hadOneofValue = false
                        if let current = _storage._attribute {
                            hadOneofValue = true
                            if case let .textAttributes(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._attribute = .textAttributes(v)
                        }
                    }()
                case 10: try {
                        var v: Entities_GifAttributes?
                        var hadOneofValue = false
                        if let current = _storage._attribute {
                            hadOneofValue = true
                            if case let .gifAttributes(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._attribute = .gifAttributes(v)
                        }
                    }()
                case 11: try {
                        var v: Entities_StickerAttributes?
                        var hadOneofValue = false
                        if let current = _storage._attribute {
                            hadOneofValue = true
                            if case let .stickerAttributes(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._attribute = .stickerAttributes(v)
                        }
                    }()
                case 12: try decoder.decodeSingularMessageField(value: &_storage._timestamp)
                default: break
                }
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            try { if let v = _storage._layerID {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            } }()
            try { if let v = _storage._postID {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
            } }()
            try { if let v = _storage._memberID {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            } }()
            if _storage._layerType != .unknown {
                try visitor.visitSingularEnumField(value: _storage._layerType, fieldNumber: 4)
            }
            if _storage._x.bitPattern != 0 {
                try visitor.visitSingularDoubleField(value: _storage._x, fieldNumber: 5)
            }
            if _storage._y.bitPattern != 0 {
                try visitor.visitSingularDoubleField(value: _storage._y, fieldNumber: 6)
            }
            if _storage._scale.bitPattern != 0 {
                try visitor.visitSingularDoubleField(value: _storage._scale, fieldNumber: 7)
            }
            if _storage._rotation.bitPattern != 0 {
                try visitor.visitSingularDoubleField(value: _storage._rotation, fieldNumber: 8)
            }
            switch _storage._attribute {
            case .textAttributes?: try {
                    guard case let .textAttributes(v)? = _storage._attribute else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
                }()
            case .gifAttributes?: try {
                    guard case let .gifAttributes(v)? = _storage._attribute else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
                }()
            case .stickerAttributes?: try {
                    guard case let .stickerAttributes(v)? = _storage._attribute else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
                }()
            case nil: break
            }
            try { if let v = _storage._timestamp {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
            } }()
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_LayerEntity, rhs: Entities_LayerEntity) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._layerID != rhs_storage._layerID { return false }
                if _storage._postID != rhs_storage._postID { return false }
                if _storage._memberID != rhs_storage._memberID { return false }
                if _storage._layerType != rhs_storage._layerType { return false }
                if _storage._x != rhs_storage._x { return false }
                if _storage._y != rhs_storage._y { return false }
                if _storage._scale != rhs_storage._scale { return false }
                if _storage._rotation != rhs_storage._rotation { return false }
                if _storage._attribute != rhs_storage._attribute { return false }
                if _storage._timestamp != rhs_storage._timestamp { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Entities_TextAttributes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".TextAttributes"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "text"),
        2: .same(proto: "fontStyle"),
        3: .same(proto: "fontColor"),
        4: .same(proto: "fontSize"),
        5: .same(proto: "backgroundStyle"),
        6: .same(proto: "backgroundColor"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &text)
            case 2: try decoder.decodeSingularStringField(value: &fontStyle)
            case 3: try decoder.decodeSingularStringField(value: &fontColor)
            case 4: try decoder.decodeSingularDoubleField(value: &fontSize)
            case 5: try decoder.decodeSingularStringField(value: &backgroundStyle)
            case 6: try decoder.decodeSingularStringField(value: &backgroundColor)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if !fontStyle.isEmpty {
            try visitor.visitSingularStringField(value: fontStyle, fieldNumber: 2)
        }
        if !fontColor.isEmpty {
            try visitor.visitSingularStringField(value: fontColor, fieldNumber: 3)
        }
        if fontSize.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: fontSize, fieldNumber: 4)
        }
        if !backgroundStyle.isEmpty {
            try visitor.visitSingularStringField(value: backgroundStyle, fieldNumber: 5)
        }
        if !backgroundColor.isEmpty {
            try visitor.visitSingularStringField(value: backgroundColor, fieldNumber: 6)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_TextAttributes, rhs: Entities_TextAttributes) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.fontStyle != rhs.fontStyle { return false }
        if lhs.fontColor != rhs.fontColor { return false }
        if lhs.fontSize != rhs.fontSize { return false }
        if lhs.backgroundStyle != rhs.backgroundStyle { return false }
        if lhs.backgroundColor != rhs.backgroundColor { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Entities_GifAttributes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GifAttributes"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "url"),
        2: .same(proto: "width"),
        3: .same(proto: "height"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &url)
            case 2: try decoder.decodeSingularDoubleField(value: &width)
            case 3: try decoder.decodeSingularDoubleField(value: &height)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !url.isEmpty {
            try visitor.visitSingularStringField(value: url, fieldNumber: 1)
        }
        if width.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: width, fieldNumber: 2)
        }
        if height.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: height, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_GifAttributes, rhs: Entities_GifAttributes) -> Bool {
        if lhs.url != rhs.url { return false }
        if lhs.width != rhs.width { return false }
        if lhs.height != rhs.height { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Entities_StickerAttributes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".StickerAttributes"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "url"),
        2: .same(proto: "width"),
        3: .same(proto: "height"),
        4: .same(proto: "rotation"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &url)
            case 2: try decoder.decodeSingularDoubleField(value: &width)
            case 3: try decoder.decodeSingularDoubleField(value: &height)
            case 4: try decoder.decodeSingularDoubleField(value: &rotation)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !url.isEmpty {
            try visitor.visitSingularStringField(value: url, fieldNumber: 1)
        }
        if width.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: width, fieldNumber: 2)
        }
        if height.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: height, fieldNumber: 3)
        }
        if rotation.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: rotation, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_StickerAttributes, rhs: Entities_StickerAttributes) -> Bool {
        if lhs.url != rhs.url { return false }
        if lhs.width != rhs.width { return false }
        if lhs.height != rhs.height { return false }
        if lhs.rotation != rhs.rotation { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
