// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/media_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Entities_MediaEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var mediaID: Common_MediaId {
        get { return _mediaID ?? Common_MediaId() }
        set { _mediaID = newValue }
    }

    /// Returns true if `mediaID` has been explicitly set.
    public var hasMediaID: Bool { return _mediaID != nil }
    /// Clears the value of `mediaID`. Subsequent reads from it will return its default value.
    public mutating func clearMediaID() { _mediaID = nil }

    public var mediaType: Common_MediaType = .unknown

    public var duration: Double = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _mediaID: Common_MediaId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_MediaEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".MediaEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "media_id"),
        2: .standard(proto: "media_type"),
        3: .same(proto: "duration"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_mediaID)
            case 2: try decoder.decodeSingularEnumField(value: &mediaType)
            case 3: try decoder.decodeSingularDoubleField(value: &duration)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._mediaID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if mediaType != .unknown {
            try visitor.visitSingularEnumField(value: mediaType, fieldNumber: 2)
        }
        if duration.bitPattern != 0 {
            try visitor.visitSingularDoubleField(value: duration, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_MediaEntity, rhs: Entities_MediaEntity) -> Bool {
        if lhs._mediaID != rhs._mediaID { return false }
        if lhs.mediaType != rhs.mediaType { return false }
        if lhs.duration != rhs.duration { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
