// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/post_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Entities_PostEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var postID: Common_PostId {
        get { return _postID ?? Common_PostId() }
        set { _postID = newValue }
    }

    /// Returns true if `postID` has been explicitly set.
    public var hasPostID: Bool { return _postID != nil }
    /// Clears the value of `postID`. Subsequent reads from it will return its default value.
    public mutating func clearPostID() { _postID = nil }

    public var chatID: Common_ChatId {
        get { return _chatID ?? Common_ChatId() }
        set { _chatID = newValue }
    }

    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool { return _chatID != nil }
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() { _chatID = nil }

    public var memberID: Common_ChatMemberId {
        get { return _memberID ?? Common_ChatMemberId() }
        set { _memberID = newValue }
    }

    /// Returns true if `memberID` has been explicitly set.
    public var hasMemberID: Bool { return _memberID != nil }
    /// Clears the value of `memberID`. Subsequent reads from it will return its default value.
    public mutating func clearMemberID() { _memberID = nil }

    public var postType: Common_PostType = .unknown

    public var mediaEntity: Entities_MediaEntity {
        get { return _mediaEntity ?? Entities_MediaEntity() }
        set { _mediaEntity = newValue }
    }

    /// Returns true if `mediaEntity` has been explicitly set.
    public var hasMediaEntity: Bool { return _mediaEntity != nil }
    /// Clears the value of `mediaEntity`. Subsequent reads from it will return its default value.
    public mutating func clearMediaEntity() { _mediaEntity = nil }

    public var title: String = .init()

    public var descriptionText: String = .init()

    public var replyEntity: Entities_ReplyEntity {
        get { return _replyEntity ?? Entities_ReplyEntity() }
        set { _replyEntity = newValue }
    }

    /// Returns true if `replyEntity` has been explicitly set.
    public var hasReplyEntity: Bool { return _replyEntity != nil }
    /// Clears the value of `replyEntity`. Subsequent reads from it will return its default value.
    public mutating func clearReplyEntity() { _replyEntity = nil }

    public var timestamp: Common_Timestamp {
        get { return _timestamp ?? Common_Timestamp() }
        set { _timestamp = newValue }
    }

    /// Returns true if `timestamp` has been explicitly set.
    public var hasTimestamp: Bool { return _timestamp != nil }
    /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
    public mutating func clearTimestamp() { _timestamp = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _postID: Common_PostId?
    fileprivate var _chatID: Common_ChatId?
    fileprivate var _memberID: Common_ChatMemberId?
    fileprivate var _mediaEntity: Entities_MediaEntity?
    fileprivate var _replyEntity: Entities_ReplyEntity?
    fileprivate var _timestamp: Common_Timestamp?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_PostEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".PostEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "post_id"),
        2: .standard(proto: "chat_id"),
        3: .standard(proto: "member_id"),
        4: .standard(proto: "post_type"),
        5: .standard(proto: "media_entity"),
        6: .same(proto: "title"),
        7: .standard(proto: "description_text"),
        8: .standard(proto: "reply_entity"),
        9: .same(proto: "timestamp"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_postID)
            case 2: try decoder.decodeSingularMessageField(value: &_chatID)
            case 3: try decoder.decodeSingularMessageField(value: &_memberID)
            case 4: try decoder.decodeSingularEnumField(value: &postType)
            case 5: try decoder.decodeSingularMessageField(value: &_mediaEntity)
            case 6: try decoder.decodeSingularStringField(value: &title)
            case 7: try decoder.decodeSingularStringField(value: &descriptionText)
            case 8: try decoder.decodeSingularMessageField(value: &_replyEntity)
            case 9: try decoder.decodeSingularMessageField(value: &_timestamp)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._postID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        try { if let v = self._chatID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._memberID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        if postType != .unknown {
            try visitor.visitSingularEnumField(value: postType, fieldNumber: 4)
        }
        try { if let v = self._mediaEntity {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
        } }()
        if !title.isEmpty {
            try visitor.visitSingularStringField(value: title, fieldNumber: 6)
        }
        if !descriptionText.isEmpty {
            try visitor.visitSingularStringField(value: descriptionText, fieldNumber: 7)
        }
        try { if let v = self._replyEntity {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
        } }()
        try { if let v = self._timestamp {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_PostEntity, rhs: Entities_PostEntity) -> Bool {
        if lhs._postID != rhs._postID { return false }
        if lhs._chatID != rhs._chatID { return false }
        if lhs._memberID != rhs._memberID { return false }
        if lhs.postType != rhs.postType { return false }
        if lhs._mediaEntity != rhs._mediaEntity { return false }
        if lhs.title != rhs.title { return false }
        if lhs.descriptionText != rhs.descriptionText { return false }
        if lhs._replyEntity != rhs._replyEntity { return false }
        if lhs._timestamp != rhs._timestamp { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
