// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/public_user_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Entities_PublicUserEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var userID: Common_UserId {
        get { return _userID ?? Common_UserId() }
        set { _userID = newValue }
    }

    /// Returns true if `userID` has been explicitly set.
    public var hasUserID: Bool { return _userID != nil }
    /// Clears the value of `userID`. Subsequent reads from it will return its default value.
    public mutating func clearUserID() { _userID = nil }

    public var firstName: String = .init()

    public var lastName: String = .init()

    public var avatar: String = .init()

    public var phone: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _userID: Common_UserId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_PublicUserEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".PublicUserEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "user_id"),
        2: .standard(proto: "first_name"),
        3: .standard(proto: "last_name"),
        4: .same(proto: "avatar"),
        5: .same(proto: "phone"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_userID)
            case 2: try decoder.decodeSingularStringField(value: &firstName)
            case 3: try decoder.decodeSingularStringField(value: &lastName)
            case 4: try decoder.decodeSingularStringField(value: &avatar)
            case 5: try decoder.decodeSingularStringField(value: &phone)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._userID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if !firstName.isEmpty {
            try visitor.visitSingularStringField(value: firstName, fieldNumber: 2)
        }
        if !lastName.isEmpty {
            try visitor.visitSingularStringField(value: lastName, fieldNumber: 3)
        }
        if !avatar.isEmpty {
            try visitor.visitSingularStringField(value: avatar, fieldNumber: 4)
        }
        if !phone.isEmpty {
            try visitor.visitSingularStringField(value: phone, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_PublicUserEntity, rhs: Entities_PublicUserEntity) -> Bool {
        if lhs._userID != rhs._userID { return false }
        if lhs.firstName != rhs.firstName { return false }
        if lhs.lastName != rhs.lastName { return false }
        if lhs.avatar != rhs.avatar { return false }
        if lhs.phone != rhs.phone { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
