// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/public_user_activity_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Entities_PublicUserActivityEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var userActivityID: Common_UserActivityId {
        get { return _userActivityID ?? Common_UserActivityId() }
        set { _userActivityID = newValue }
    }

    /// Returns true if `userActivityID` has been explicitly set.
    public var hasUserActivityID: Bool { return _userActivityID != nil }
    /// Clears the value of `userActivityID`. Subsequent reads from it will return its default value.
    public mutating func clearUserActivityID() { _userActivityID = nil }

    public var userStatus: Common_UserStatus = .unknown

    public var lastActiveAt: Common_Timestamp {
        get { return _lastActiveAt ?? Common_Timestamp() }
        set { _lastActiveAt = newValue }
    }

    /// Returns true if `lastActiveAt` has been explicitly set.
    public var hasLastActiveAt: Bool { return _lastActiveAt != nil }
    /// Clears the value of `lastActiveAt`. Subsequent reads from it will return its default value.
    public mutating func clearLastActiveAt() { _lastActiveAt = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _userActivityID: Common_UserActivityId?
    fileprivate var _lastActiveAt: Common_Timestamp?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_PublicUserActivityEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".PublicUserActivityEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "user_activity_id"),
        2: .standard(proto: "user_status"),
        3: .standard(proto: "last_active_at"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_userActivityID)
            case 2: try decoder.decodeSingularEnumField(value: &userStatus)
            case 3: try decoder.decodeSingularMessageField(value: &_lastActiveAt)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._userActivityID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if userStatus != .unknown {
            try visitor.visitSingularEnumField(value: userStatus, fieldNumber: 2)
        }
        try { if let v = self._lastActiveAt {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_PublicUserActivityEntity, rhs: Entities_PublicUserActivityEntity) -> Bool {
        if lhs._userActivityID != rhs._userActivityID { return false }
        if lhs.userStatus != rhs.userStatus { return false }
        if lhs._lastActiveAt != rhs._lastActiveAt { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
