// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/public_chat_member.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Entities_PublicChatMemberEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var memberID: Common_ChatMemberId {
        get { return _memberID ?? Common_ChatMemberId() }
        set { _memberID = newValue }
    }

    /// Returns true if `memberID` has been explicitly set.
    public var hasMemberID: Bool { return _memberID != nil }
    /// Clears the value of `memberID`. Subsequent reads from it will return its default value.
    public mutating func clearMemberID() { _memberID = nil }

    public var chatID: Common_ChatId {
        get { return _chatID ?? Common_ChatId() }
        set { _chatID = newValue }
    }

    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool { return _chatID != nil }
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() { _chatID = nil }

    public var userID: Common_UserId {
        get { return _userID ?? Common_UserId() }
        set { _userID = newValue }
    }

    /// Returns true if `userID` has been explicitly set.
    public var hasUserID: Bool { return _userID != nil }
    /// Clears the value of `userID`. Subsequent reads from it will return its default value.
    public mutating func clearUserID() { _userID = nil }

    public var role: Common_MemberRole = .unknown

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _memberID: Common_ChatMemberId?
    fileprivate var _chatID: Common_ChatId?
    fileprivate var _userID: Common_UserId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_PublicChatMemberEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".PublicChatMemberEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "member_id"),
        2: .standard(proto: "chat_id"),
        3: .standard(proto: "user_id"),
        4: .same(proto: "role"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_memberID)
            case 2: try decoder.decodeSingularMessageField(value: &_chatID)
            case 3: try decoder.decodeSingularMessageField(value: &_userID)
            case 4: try decoder.decodeSingularEnumField(value: &role)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._memberID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        try { if let v = self._chatID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._userID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        if role != .unknown {
            try visitor.visitSingularEnumField(value: role, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_PublicChatMemberEntity, rhs: Entities_PublicChatMemberEntity) -> Bool {
        if lhs._memberID != rhs._memberID { return false }
        if lhs._chatID != rhs._chatID { return false }
        if lhs._userID != rhs._userID { return false }
        if lhs.role != rhs.role { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
