// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: entities/reply_entity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Entities_ReplyEntity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var replyToID: Common_ReplyToId {
        get { return _replyToID ?? Common_ReplyToId() }
        set { _replyToID = newValue }
    }

    /// Returns true if `replyToID` has been explicitly set.
    public var hasReplyToID: Bool { return _replyToID != nil }
    /// Clears the value of `replyToID`. Subsequent reads from it will return its default value.
    public mutating func clearReplyToID() { _replyToID = nil }

    public var replyEntityType: Common_ChatEntityType = .chatUnknown

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _replyToID: Common_ReplyToId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "entities"

extension Entities_ReplyEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ReplyEntity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "reply_to_id"),
        2: .standard(proto: "reply_entity_type"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_replyToID)
            case 2: try decoder.decodeSingularEnumField(value: &replyEntityType)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._replyToID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if replyEntityType != .chatUnknown {
            try visitor.visitSingularEnumField(value: replyEntityType, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Entities_ReplyEntity, rhs: Entities_ReplyEntity) -> Bool {
        if lhs._replyToID != rhs._replyToID { return false }
        if lhs.replyEntityType != rhs.replyEntityType { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
