// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common/enums.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public enum Common_DeliveryStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case uploading // = 1
    case sending // = 2
    case sent // = 3
    case delivered // = 4
    case read // = 5
    case failed // = 6
    case deleted // = 7
    case edited // = 8
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .uploading
        case 2: self = .sending
        case 3: self = .sent
        case 4: self = .delivered
        case 5: self = .read
        case 6: self = .failed
        case 7: self = .deleted
        case 8: self = .edited
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .uploading: return 1
        case .sending: return 2
        case .sent: return 3
        case .delivered: return 4
        case .read: return 5
        case .failed: return 6
        case .deleted: return 7
        case .edited: return 8
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_DeliveryStatus] = [
        .unknown,
        .uploading,
        .sending,
        .sent,
        .delivered,
        .read,
        .failed,
        .deleted,
        .edited,
    ]
}

public enum Common_ChatType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case dialogue // = 1
    case group // = 2
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .dialogue
        case 2: self = .group
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .dialogue: return 1
        case .group: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_ChatType] = [
        .unknown,
        .dialogue,
        .group,
    ]
}

public enum Common_ChatEntityType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case chatUnknown // = 0
    case post // = 1
    case comment // = 2
    case UNRECOGNIZED(Int)

    public init() {
        self = .chatUnknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .chatUnknown
        case 1: self = .post
        case 2: self = .comment
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .chatUnknown: return 0
        case .post: return 1
        case .comment: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_ChatEntityType] = [
        .chatUnknown,
        .post,
        .comment,
    ]
}

public enum Common_LayerType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case text // = 1
    case gif // = 2
    case sticker // = 3
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .text
        case 2: self = .gif
        case 3: self = .sticker
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .text: return 1
        case .gif: return 2
        case .sticker: return 3
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_LayerType] = [
        .unknown,
        .text,
        .gif,
        .sticker,
    ]
}

public enum Common_UserStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case online // = 1
    case offline // = 2
    case typing // = 3
    case active // = 4
    case capturing // = 5
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .online
        case 2: self = .offline
        case 3: self = .typing
        case 4: self = .active
        case 5: self = .capturing
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .online: return 1
        case .offline: return 2
        case .typing: return 3
        case .active: return 4
        case .capturing: return 5
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_UserStatus] = [
        .unknown,
        .online,
        .offline,
        .typing,
        .active,
        .capturing,
    ]
}

public enum Common_MediaType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case video // = 1
    case image // = 2
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .video
        case 2: self = .image
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .video: return 1
        case .image: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_MediaType] = [
        .unknown,
        .video,
        .image,
    ]
}

public enum Common_MemberRole: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case owner // = 1
    case member // = 2
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .owner
        case 2: self = .member
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .owner: return 1
        case .member: return 2
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_MemberRole] = [
        .unknown,
        .owner,
        .member,
    ]
}

public enum Common_PostType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case bubble // = 1
    case frame // = 2
    case topic // = 3
    case UNRECOGNIZED(Int)

    public init() {
        self = .unknown
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .unknown
        case 1: self = .bubble
        case 2: self = .frame
        case 3: self = .topic
        default: self = .UNRECOGNIZED(rawValue)
        }
    }

    public var rawValue: Int {
        switch self {
        case .unknown: return 0
        case .bubble: return 1
        case .frame: return 2
        case .topic: return 3
        case let .UNRECOGNIZED(i): return i
        }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Common_PostType] = [
        .unknown,
        .bubble,
        .frame,
        .topic,
    ]
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Common_DeliveryStatus: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "DELIVERY_STATUS_UNKNOWN"),
        1: .same(proto: "UPLOADING"),
        2: .same(proto: "SENDING"),
        3: .same(proto: "SENT"),
        4: .same(proto: "DELIVERED"),
        5: .same(proto: "READ"),
        6: .same(proto: "FAILED"),
        7: .same(proto: "DELETED"),
        8: .same(proto: "EDITED"),
    ]
}

extension Common_ChatType: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "CHAT_TYPE_UNKNOWN"),
        1: .same(proto: "DIALOGUE"),
        2: .same(proto: "GROUP"),
    ]
}

extension Common_ChatEntityType: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "CHAT_UNKNOWN"),
        1: .same(proto: "POST"),
        2: .same(proto: "COMMENT"),
    ]
}

extension Common_LayerType: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "LAYER_TYPE_UNKNOWN"),
        1: .same(proto: "TEXT"),
        2: .same(proto: "GIF"),
        3: .same(proto: "STICKER"),
    ]
}

extension Common_UserStatus: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "USER_STATUS_UNKNOWN"),
        1: .same(proto: "ONLINE"),
        2: .same(proto: "OFFLINE"),
        3: .same(proto: "TYPING"),
        4: .same(proto: "ACTIVE"),
        5: .same(proto: "CAPTURING"),
    ]
}

extension Common_MediaType: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "MEDIA_TYPE_UNKNOWN"),
        1: .same(proto: "VIDEO"),
        2: .same(proto: "IMAGE"),
    ]
}

extension Common_MemberRole: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "MEMBER_ROLE_UNKNOWN"),
        1: .same(proto: "OWNER"),
        2: .same(proto: "MEMBER"),
    ]
}

extension Common_PostType: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        0: .same(proto: "POST_TYPE_UNKNOWN"),
        1: .same(proto: "BUBBLE"),
        2: .same(proto: "FRAME"),
        3: .same(proto: "TOPIC"),
    ]
}
