// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common/identifiers.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

/// Request identifier
public struct Common_RequestId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var value: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_ReplyToId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

/// User identifier
public struct Common_UserId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_UserActivityId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_ChatId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_PostId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_MediaId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_CommentId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_ChatMemberId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_ReactionId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_LayerId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_ContactId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Common_DeliveryTrackId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var server: String = .init()

    public var client: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "common"

extension Common_RequestId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RequestId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "value"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &value)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !value.isEmpty {
            try visitor.visitSingularStringField(value: value, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_RequestId, rhs: Common_RequestId) -> Bool {
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_ReplyToId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ReplyToId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_ReplyToId, rhs: Common_ReplyToId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_UserId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UserId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_UserId, rhs: Common_UserId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_UserActivityId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UserActivityId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_UserActivityId, rhs: Common_UserActivityId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_ChatId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ChatId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_ChatId, rhs: Common_ChatId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_PostId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".PostId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_PostId, rhs: Common_PostId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_MediaId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".MediaId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_MediaId, rhs: Common_MediaId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_CommentId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".CommentId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_CommentId, rhs: Common_CommentId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_ChatMemberId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ChatMemberId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_ChatMemberId, rhs: Common_ChatMemberId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_ReactionId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ReactionId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_ReactionId, rhs: Common_ReactionId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_LayerId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".LayerId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_LayerId, rhs: Common_LayerId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_ContactId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ContactId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_ContactId, rhs: Common_ContactId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Common_DeliveryTrackId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".DeliveryTrackId"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "server"),
        2: .same(proto: "client"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &server)
            case 2: try decoder.decodeSingularStringField(value: &client)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !server.isEmpty {
            try visitor.visitSingularStringField(value: server, fieldNumber: 1)
        }
        if !client.isEmpty {
            try visitor.visitSingularStringField(value: client, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Common_DeliveryTrackId, rhs: Common_DeliveryTrackId) -> Bool {
        if lhs.server != rhs.server { return false }
        if lhs.client != rhs.client { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
