// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: responses/client_responses.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Responses_ClientResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// ID of the corresponding request
    public var requestID: Common_RequestId {
        get { return _requestID ?? Common_RequestId() }
        set { _requestID = newValue }
    }

    /// Returns true if `requestID` has been explicitly set.
    public var hasRequestID: Bool { return _requestID != nil }
    /// Clears the value of `requestID`. Subsequent reads from it will return its default value.
    public mutating func clearRequestID() { _requestID = nil }

    /// Whether the operation succeeded
    public var success: Bool = false

    /// Error description if unsuccessful
    public var errorMessage: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _requestID: Common_RequestId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "responses"

extension Responses_ClientResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ClientResponse"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "request_id"),
        2: .same(proto: "success"),
        3: .standard(proto: "error_message"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_requestID)
            case 2: try decoder.decodeSingularBoolField(value: &success)
            case 3: try decoder.decodeSingularStringField(value: &errorMessage)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._requestID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if success != false {
            try visitor.visitSingularBoolField(value: success, fieldNumber: 2)
        }
        if !errorMessage.isEmpty {
            try visitor.visitSingularStringField(value: errorMessage, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Responses_ClientResponse, rhs: Responses_ClientResponse) -> Bool {
        if lhs._requestID != rhs._requestID { return false }
        if lhs.success != rhs.success { return false }
        if lhs.errorMessage != rhs.errorMessage { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
