// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: responses/contact_responses.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct ContactResponses_ContactWithUserActivity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var contactID: Common_ContactId {
        get { return _contactID ?? Common_ContactId() }
        set { _contactID = newValue }
    }

    /// Returns true if `contactID` has been explicitly set.
    public var hasContactID: Bool { return _contactID != nil }
    /// Clears the value of `contactID`. Subsequent reads from it will return its default value.
    public mutating func clearContactID() { _contactID = nil }

    public var user: Entities_PublicUserEntity {
        get { return _user ?? Entities_PublicUserEntity() }
        set { _user = newValue }
    }

    /// Returns true if `user` has been explicitly set.
    public var hasUser: Bool { return _user != nil }
    /// Clears the value of `user`. Subsequent reads from it will return its default value.
    public mutating func clearUser() { _user = nil }

    public var userActivity: Entities_PublicUserActivityEntity {
        get { return _userActivity ?? Entities_PublicUserActivityEntity() }
        set { _userActivity = newValue }
    }

    /// Returns true if `userActivity` has been explicitly set.
    public var hasUserActivity: Bool { return _userActivity != nil }
    /// Clears the value of `userActivity`. Subsequent reads from it will return its default value.
    public mutating func clearUserActivity() { _userActivity = nil }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _contactID: Common_ContactId?
    fileprivate var _user: Entities_PublicUserEntity?
    fileprivate var _userActivity: Entities_PublicUserActivityEntity?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "contact_responses"

extension ContactResponses_ContactWithUserActivity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ContactWithUserActivity"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "contact_id"),
        2: .same(proto: "user"),
        3: .standard(proto: "user_activity"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_contactID)
            case 2: try decoder.decodeSingularMessageField(value: &_user)
            case 3: try decoder.decodeSingularMessageField(value: &_userActivity)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._contactID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        try { if let v = self._user {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._userActivity {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: ContactResponses_ContactWithUserActivity, rhs: ContactResponses_ContactWithUserActivity) -> Bool {
        if lhs._contactID != rhs._contactID { return false }
        if lhs._user != rhs._user { return false }
        if lhs._userActivity != rhs._userActivity { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
