// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: requests/client_requests.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Requests_ClientRequest: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var requestID: Common_RequestId {
        get { return _storage._requestID ?? Common_RequestId() }
        set { _uniqueStorage()._requestID = newValue }
    }

    /// Returns true if `requestID` has been explicitly set.
    public var hasRequestID: Bool { return _storage._requestID != nil }
    /// Clears the value of `requestID`. Subsequent reads from it will return its default value.
    public mutating func clearRequestID() { _uniqueStorage()._requestID = nil }

    public var payload: OneOf_Payload? {
        get { return _storage._payload }
        set { _uniqueStorage()._payload = newValue }
    }

    public var requestSendPost: Entities_PostEntity {
        get {
            if case let .requestSendPost(v)? = _storage._payload { return v }
            return Entities_PostEntity()
        }
        set { _uniqueStorage()._payload = .requestSendPost(newValue) }
    }

    public var requestSendComment: Entities_CommentEntity {
        get {
            if case let .requestSendComment(v)? = _storage._payload { return v }
            return Entities_CommentEntity()
        }
        set { _uniqueStorage()._payload = .requestSendComment(newValue) }
    }

    public var requestSendLayer: Entities_LayerEntity {
        get {
            if case let .requestSendLayer(v)? = _storage._payload { return v }
            return Entities_LayerEntity()
        }
        set { _uniqueStorage()._payload = .requestSendLayer(newValue) }
    }

    public var requestSendReaction: Entities_ReactionEntity {
        get {
            if case let .requestSendReaction(v)? = _storage._payload { return v }
            return Entities_ReactionEntity()
        }
        set { _uniqueStorage()._payload = .requestSendReaction(newValue) }
    }

    public var requestSendStatus: CommonRequests_DeliveryStatusPayload {
        get {
            if case let .requestSendStatus(v)? = _storage._payload { return v }
            return CommonRequests_DeliveryStatusPayload()
        }
        set { _uniqueStorage()._payload = .requestSendStatus(newValue) }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Payload: Equatable, Sendable {
        case requestSendPost(Entities_PostEntity)
        case requestSendComment(Entities_CommentEntity)
        case requestSendLayer(Entities_LayerEntity)
        case requestSendReaction(Entities_ReactionEntity)
        case requestSendStatus(CommonRequests_DeliveryStatusPayload)
    }

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "requests"

extension Requests_ClientRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ClientRequest"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "request_id"),
        2: .standard(proto: "request_send_post"),
        3: .standard(proto: "request_send_comment"),
        4: .standard(proto: "request_send_layer"),
        5: .standard(proto: "request_send_reaction"),
        6: .standard(proto: "request_send_status"),
    ]

    fileprivate class _StorageClass {
        var _requestID: Common_RequestId?
        var _payload: Requests_ClientRequest.OneOf_Payload?

        #if swift(>=5.10)
            // This property is used as the initial default value for new instances of the type.
            // The type itself is protecting the reference to its storage via CoW semantics.
            // This will force a copy to be made of this reference when the first mutation occurs;
            // hence, it is safe to mark this as `nonisolated(unsafe)`.
            nonisolated(unsafe) static let defaultInstance = _StorageClass()
        #else
            static let defaultInstance = _StorageClass()
        #endif

        private init() {}

        init(copying source: _StorageClass) {
            _requestID = source._requestID
            _payload = source._payload
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_storage._requestID)
                case 2: try {
                        var v: Entities_PostEntity?
                        var hadOneofValue = false
                        if let current = _storage._payload {
                            hadOneofValue = true
                            if case let .requestSendPost(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._payload = .requestSendPost(v)
                        }
                    }()
                case 3: try {
                        var v: Entities_CommentEntity?
                        var hadOneofValue = false
                        if let current = _storage._payload {
                            hadOneofValue = true
                            if case let .requestSendComment(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._payload = .requestSendComment(v)
                        }
                    }()
                case 4: try {
                        var v: Entities_LayerEntity?
                        var hadOneofValue = false
                        if let current = _storage._payload {
                            hadOneofValue = true
                            if case let .requestSendLayer(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._payload = .requestSendLayer(v)
                        }
                    }()
                case 5: try {
                        var v: Entities_ReactionEntity?
                        var hadOneofValue = false
                        if let current = _storage._payload {
                            hadOneofValue = true
                            if case let .requestSendReaction(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._payload = .requestSendReaction(v)
                        }
                    }()
                case 6: try {
                        var v: CommonRequests_DeliveryStatusPayload?
                        var hadOneofValue = false
                        if let current = _storage._payload {
                            hadOneofValue = true
                            if case let .requestSendStatus(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v = v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            _storage._payload = .requestSendStatus(v)
                        }
                    }()
                default: break
                }
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            try { if let v = _storage._requestID {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            } }()
            switch _storage._payload {
            case .requestSendPost?: try {
                    guard case let .requestSendPost(v)? = _storage._payload else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
                }()
            case .requestSendComment?: try {
                    guard case let .requestSendComment(v)? = _storage._payload else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
                }()
            case .requestSendLayer?: try {
                    guard case let .requestSendLayer(v)? = _storage._payload else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
                }()
            case .requestSendReaction?: try {
                    guard case let .requestSendReaction(v)? = _storage._payload else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
                }()
            case .requestSendStatus?: try {
                    guard case let .requestSendStatus(v)? = _storage._payload else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
                }()
            case nil: break
            }
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Requests_ClientRequest, rhs: Requests_ClientRequest) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._requestID != rhs_storage._requestID { return false }
                if _storage._payload != rhs_storage._payload { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
