// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: requests/contact_requests.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct ContactRequests_UploadContact: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var contactID: Common_ContactId {
        get { return _contactID ?? Common_ContactId() }
        set { _contactID = newValue }
    }

    /// Returns true if `contactID` has been explicitly set.
    public var hasContactID: Bool { return _contactID != nil }
    /// Clears the value of `contactID`. Subsequent reads from it will return its default value.
    public mutating func clearContactID() { _contactID = nil }

    public var givenName: String = .init()

    public var familyName: String = .init()

    public var phoneNumbers: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _contactID: Common_ContactId?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "contact_requests"

extension ContactRequests_UploadContact: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UploadContact"
    public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .standard(proto: "contact_id"),
        2: .standard(proto: "given_name"),
        3: .standard(proto: "family_name"),
        4: .standard(proto: "phone_numbers"),
    ]

    public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_contactID)
            case 2: try decoder.decodeSingularStringField(value: &givenName)
            case 3: try decoder.decodeSingularStringField(value: &familyName)
            case 4: try decoder.decodeRepeatedStringField(value: &phoneNumbers)
            default: break
            }
        }
    }

    public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        try { if let v = self._contactID {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        } }()
        if !givenName.isEmpty {
            try visitor.visitSingularStringField(value: givenName, fieldNumber: 2)
        }
        if !familyName.isEmpty {
            try visitor.visitSingularStringField(value: familyName, fieldNumber: 3)
        }
        if !phoneNumbers.isEmpty {
            try visitor.visitRepeatedStringField(value: phoneNumbers, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: ContactRequests_UploadContact, rhs: ContactRequests_UploadContact) -> Bool {
        if lhs._contactID != rhs._contactID { return false }
        if lhs.givenName != rhs.givenName { return false }
        if lhs.familyName != rhs.familyName { return false }
        if lhs.phoneNumbers != rhs.phoneNumbers { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
