//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: services/client_to_server.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

/// Usage: instantiate `Services_ClientToServerStreamClient`, then call methods of this protocol to make API calls.
public protocol Services_ClientToServerStreamClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? { get }

    func clientStream(
        callOptions: CallOptions?,
        handler: @escaping (Responses_ServerResponse) -> Void
    ) -> BidirectionalStreamingCall<Requests_ClientRequest, Responses_ServerResponse>
}

public extension Services_ClientToServerStreamClientProtocol {
    var serviceName: String {
        return "services.ClientToServerStream"
    }

    /// Bidirectional streaming call to ClientStream
    ///
    /// Callers should use the `send` method on the returned object to send messages
    /// to the server. The caller should send an `.end` after the final message has been sent.
    ///
    /// - Parameters:
    ///   - callOptions: Call options.
    ///   - handler: A closure called when each response is received from the server.
    /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
    func clientStream(
        callOptions: CallOptions? = nil,
        handler: @escaping (Responses_ServerResponse) -> Void
    ) -> BidirectionalStreamingCall<Requests_ClientRequest, Responses_ServerResponse> {
        return makeBidirectionalStreamingCall(
            path: Services_ClientToServerStreamClientMetadata.Methods.clientStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeClientStreamInterceptors() ?? [],
            handler: handler
        )
    }
}

@available(*, deprecated)
extension Services_ClientToServerStreamClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Services_ClientToServerStreamNIOClient")
public final class Services_ClientToServerStreamClient: Services_ClientToServerStreamClientProtocol {
    private let lock = Lock()
    private var _defaultCallOptions: CallOptions
    private var _interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol?
    public let channel: GRPCChannel
    public var defaultCallOptions: CallOptions {
        get { lock.withLock { self._defaultCallOptions } }
        set { lock.withLockVoid { self._defaultCallOptions = newValue } }
    }

    public var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? {
        get { lock.withLock { self._interceptors } }
        set { lock.withLockVoid { self._interceptors = newValue } }
    }

    /// Creates a client for the services.ClientToServerStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        _defaultCallOptions = defaultCallOptions
        _interceptors = interceptors
    }
}

public struct Services_ClientToServerStreamNIOClient: Services_ClientToServerStreamClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol?

    /// Creates a client for the services.ClientToServerStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ClientToServerStreamAsyncClientProtocol: GRPCClient {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? { get }

    func makeClientStreamCall(
        callOptions: CallOptions?
    ) -> GRPCAsyncBidirectionalStreamingCall<Requests_ClientRequest, Responses_ServerResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ClientToServerStreamAsyncClientProtocol {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ClientToServerStreamClientMetadata.serviceDescriptor
    }

    var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? {
        return nil
    }

    func makeClientStreamCall(
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncBidirectionalStreamingCall<Requests_ClientRequest, Responses_ServerResponse> {
        return makeAsyncBidirectionalStreamingCall(
            path: Services_ClientToServerStreamClientMetadata.Methods.clientStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeClientStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ClientToServerStreamAsyncClientProtocol {
    func clientStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<Responses_ServerResponse> where RequestStream: Sequence, RequestStream.Element == Requests_ClientRequest {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ClientToServerStreamClientMetadata.Methods.clientStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeClientStreamInterceptors() ?? []
        )
    }

    func clientStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<Responses_ServerResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Requests_ClientRequest {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ClientToServerStreamClientMetadata.Methods.clientStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeClientStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Services_ClientToServerStreamAsyncClient: Services_ClientToServerStreamAsyncClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol?

    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ClientToServerStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

public protocol Services_ClientToServerStreamClientInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when invoking 'clientStream'.
    func makeClientStreamInterceptors() -> [ClientInterceptor<Requests_ClientRequest, Responses_ServerResponse>]
}

public enum Services_ClientToServerStreamClientMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ClientToServerStream",
        fullName: "services.ClientToServerStream",
        methods: [
            Services_ClientToServerStreamClientMetadata.Methods.clientStream,
        ]
    )

    public enum Methods {
        public static let clientStream = GRPCMethodDescriptor(
            name: "ClientStream",
            path: "/services.ClientToServerStream/ClientStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Services_ClientToServerStreamProvider: CallHandlerProvider {
    var interceptors: Services_ClientToServerStreamServerInterceptorFactoryProtocol? { get }

    func clientStream(context: StreamingResponseCallContext<Responses_ServerResponse>) -> EventLoopFuture<(StreamEvent<Requests_ClientRequest>) -> Void>
}

public extension Services_ClientToServerStreamProvider {
    var serviceName: Substring {
        return Services_ClientToServerStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    /// Determines, calls and returns the appropriate request handler, depending on the request's method.
    /// Returns nil for methods not handled by this service.
    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ClientStream":
            return BidirectionalStreamingServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<Requests_ClientRequest>(),
                responseSerializer: ProtobufSerializer<Responses_ServerResponse>(),
                interceptors: interceptors?.makeClientStreamInterceptors() ?? [],
                observerFactory: clientStream(context:)
            )

        default:
            return nil
        }
    }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ClientToServerStreamAsyncProvider: CallHandlerProvider, Sendable {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ClientToServerStreamServerInterceptorFactoryProtocol? { get }

    func clientStream(
        requestStream: GRPCAsyncRequestStream<Requests_ClientRequest>,
        responseStream: GRPCAsyncResponseStreamWriter<Responses_ServerResponse>,
        context: GRPCAsyncServerCallContext
    ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ClientToServerStreamAsyncProvider {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ClientToServerStreamServerMetadata.serviceDescriptor
    }

    var serviceName: Substring {
        return Services_ClientToServerStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    var interceptors: Services_ClientToServerStreamServerInterceptorFactoryProtocol? {
        return nil
    }

    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ClientStream":
            return GRPCAsyncServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<Requests_ClientRequest>(),
                responseSerializer: ProtobufSerializer<Responses_ServerResponse>(),
                interceptors: interceptors?.makeClientStreamInterceptors() ?? [],
                wrapping: { try await self.clientStream(requestStream: $0, responseStream: $1, context: $2) }
            )

        default:
            return nil
        }
    }
}

public protocol Services_ClientToServerStreamServerInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when handling 'clientStream'.
    ///   Defaults to calling `self.makeInterceptors()`.
    func makeClientStreamInterceptors() -> [ServerInterceptor<Requests_ClientRequest, Responses_ServerResponse>]
}

public enum Services_ClientToServerStreamServerMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ClientToServerStream",
        fullName: "services.ClientToServerStream",
        methods: [
            Services_ClientToServerStreamServerMetadata.Methods.clientStream,
        ]
    )

    public enum Methods {
        public static let clientStream = GRPCMethodDescriptor(
            name: "ClientStream",
            path: "/services.ClientToServerStream/ClientStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}
