//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: services/contact_with_user_activity.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

/// Service for subscribing to user statuses
///
/// Usage: instantiate `Services_ContactWithUserActivityStreamClient`, then call methods of this protocol to make API calls.
public protocol Services_ContactWithUserActivityStreamClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? { get }

    func contactUserActivityStream(
        callOptions: CallOptions?,
        handler: @escaping (ContactResponses_ContactWithUserActivity) -> Void
    ) -> BidirectionalStreamingCall<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity>
}

public extension Services_ContactWithUserActivityStreamClientProtocol {
    var serviceName: String {
        return "services.ContactWithUserActivityStream"
    }

    /// Bidirectional streaming call to ContactUserActivityStream
    ///
    /// Callers should use the `send` method on the returned object to send messages
    /// to the server. The caller should send an `.end` after the final message has been sent.
    ///
    /// - Parameters:
    ///   - callOptions: Call options.
    ///   - handler: A closure called when each response is received from the server.
    /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
    func contactUserActivityStream(
        callOptions: CallOptions? = nil,
        handler: @escaping (ContactResponses_ContactWithUserActivity) -> Void
    ) -> BidirectionalStreamingCall<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity> {
        return makeBidirectionalStreamingCall(
            path: Services_ContactWithUserActivityStreamClientMetadata.Methods.contactUserActivityStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? [],
            handler: handler
        )
    }
}

@available(*, deprecated)
extension Services_ContactWithUserActivityStreamClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Services_ContactWithUserActivityStreamNIOClient")
public final class Services_ContactWithUserActivityStreamClient: Services_ContactWithUserActivityStreamClientProtocol {
    private let lock = Lock()
    private var _defaultCallOptions: CallOptions
    private var _interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol?
    public let channel: GRPCChannel
    public var defaultCallOptions: CallOptions {
        get { lock.withLock { self._defaultCallOptions } }
        set { lock.withLockVoid { self._defaultCallOptions = newValue } }
    }

    public var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? {
        get { lock.withLock { self._interceptors } }
        set { lock.withLockVoid { self._interceptors = newValue } }
    }

    /// Creates a client for the services.ContactWithUserActivityStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        _defaultCallOptions = defaultCallOptions
        _interceptors = interceptors
    }
}

public struct Services_ContactWithUserActivityStreamNIOClient: Services_ContactWithUserActivityStreamClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol?

    /// Creates a client for the services.ContactWithUserActivityStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

/// Service for subscribing to user statuses
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ContactWithUserActivityStreamAsyncClientProtocol: GRPCClient {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? { get }

    func makeContactUserActivityStreamCall(
        callOptions: CallOptions?
    ) -> GRPCAsyncBidirectionalStreamingCall<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ContactWithUserActivityStreamAsyncClientProtocol {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ContactWithUserActivityStreamClientMetadata.serviceDescriptor
    }

    var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? {
        return nil
    }

    func makeContactUserActivityStreamCall(
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncBidirectionalStreamingCall<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity> {
        return makeAsyncBidirectionalStreamingCall(
            path: Services_ContactWithUserActivityStreamClientMetadata.Methods.contactUserActivityStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ContactWithUserActivityStreamAsyncClientProtocol {
    func contactUserActivityStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<ContactResponses_ContactWithUserActivity> where RequestStream: Sequence, RequestStream.Element == ContactRequests_UploadContact {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ContactWithUserActivityStreamClientMetadata.Methods.contactUserActivityStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? []
        )
    }

    func contactUserActivityStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<ContactResponses_ContactWithUserActivity> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == ContactRequests_UploadContact {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ContactWithUserActivityStreamClientMetadata.Methods.contactUserActivityStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Services_ContactWithUserActivityStreamAsyncClient: Services_ContactWithUserActivityStreamAsyncClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol?

    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

public protocol Services_ContactWithUserActivityStreamClientInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when invoking 'contactUserActivityStream'.
    func makeContactUserActivityStreamInterceptors() -> [ClientInterceptor<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity>]
}

public enum Services_ContactWithUserActivityStreamClientMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ContactWithUserActivityStream",
        fullName: "services.ContactWithUserActivityStream",
        methods: [
            Services_ContactWithUserActivityStreamClientMetadata.Methods.contactUserActivityStream,
        ]
    )

    public enum Methods {
        public static let contactUserActivityStream = GRPCMethodDescriptor(
            name: "ContactUserActivityStream",
            path: "/services.ContactWithUserActivityStream/ContactUserActivityStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}

/// Service for subscribing to user statuses
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Services_ContactWithUserActivityStreamProvider: CallHandlerProvider {
    var interceptors: Services_ContactWithUserActivityStreamServerInterceptorFactoryProtocol? { get }

    func contactUserActivityStream(context: StreamingResponseCallContext<ContactResponses_ContactWithUserActivity>) -> EventLoopFuture<(StreamEvent<ContactRequests_UploadContact>) -> Void>
}

public extension Services_ContactWithUserActivityStreamProvider {
    var serviceName: Substring {
        return Services_ContactWithUserActivityStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    /// Determines, calls and returns the appropriate request handler, depending on the request's method.
    /// Returns nil for methods not handled by this service.
    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ContactUserActivityStream":
            return BidirectionalStreamingServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<ContactRequests_UploadContact>(),
                responseSerializer: ProtobufSerializer<ContactResponses_ContactWithUserActivity>(),
                interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? [],
                observerFactory: contactUserActivityStream(context:)
            )

        default:
            return nil
        }
    }
}

/// Service for subscribing to user statuses
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ContactWithUserActivityStreamAsyncProvider: CallHandlerProvider, Sendable {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ContactWithUserActivityStreamServerInterceptorFactoryProtocol? { get }

    func contactUserActivityStream(
        requestStream: GRPCAsyncRequestStream<ContactRequests_UploadContact>,
        responseStream: GRPCAsyncResponseStreamWriter<ContactResponses_ContactWithUserActivity>,
        context: GRPCAsyncServerCallContext
    ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ContactWithUserActivityStreamAsyncProvider {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ContactWithUserActivityStreamServerMetadata.serviceDescriptor
    }

    var serviceName: Substring {
        return Services_ContactWithUserActivityStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    var interceptors: Services_ContactWithUserActivityStreamServerInterceptorFactoryProtocol? {
        return nil
    }

    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ContactUserActivityStream":
            return GRPCAsyncServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<ContactRequests_UploadContact>(),
                responseSerializer: ProtobufSerializer<ContactResponses_ContactWithUserActivity>(),
                interceptors: interceptors?.makeContactUserActivityStreamInterceptors() ?? [],
                wrapping: { try await self.contactUserActivityStream(requestStream: $0, responseStream: $1, context: $2) }
            )

        default:
            return nil
        }
    }
}

public protocol Services_ContactWithUserActivityStreamServerInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when handling 'contactUserActivityStream'.
    ///   Defaults to calling `self.makeInterceptors()`.
    func makeContactUserActivityStreamInterceptors() -> [ServerInterceptor<ContactRequests_UploadContact, ContactResponses_ContactWithUserActivity>]
}

public enum Services_ContactWithUserActivityStreamServerMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ContactWithUserActivityStream",
        fullName: "services.ContactWithUserActivityStream",
        methods: [
            Services_ContactWithUserActivityStreamServerMetadata.Methods.contactUserActivityStream,
        ]
    )

    public enum Methods {
        public static let contactUserActivityStream = GRPCMethodDescriptor(
            name: "ContactUserActivityStream",
            path: "/services.ContactWithUserActivityStream/ContactUserActivityStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}
