//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: services/server_to_client.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

/// Usage: instantiate `Services_ServerToClientStreamClient`, then call methods of this protocol to make API calls.
public protocol Services_ServerToClientStreamClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? { get }

    func serverStream(
        callOptions: CallOptions?,
        handler: @escaping (Requests_ServerRequest) -> Void
    ) -> BidirectionalStreamingCall<Responses_ClientResponse, Requests_ServerRequest>
}

public extension Services_ServerToClientStreamClientProtocol {
    var serviceName: String {
        return "services.ServerToClientStream"
    }

    /// Bidirectional streaming call to ServerStream
    ///
    /// Callers should use the `send` method on the returned object to send messages
    /// to the server. The caller should send an `.end` after the final message has been sent.
    ///
    /// - Parameters:
    ///   - callOptions: Call options.
    ///   - handler: A closure called when each response is received from the server.
    /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
    func serverStream(
        callOptions: CallOptions? = nil,
        handler: @escaping (Requests_ServerRequest) -> Void
    ) -> BidirectionalStreamingCall<Responses_ClientResponse, Requests_ServerRequest> {
        return makeBidirectionalStreamingCall(
            path: Services_ServerToClientStreamClientMetadata.Methods.serverStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeServerStreamInterceptors() ?? [],
            handler: handler
        )
    }
}

@available(*, deprecated)
extension Services_ServerToClientStreamClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Services_ServerToClientStreamNIOClient")
public final class Services_ServerToClientStreamClient: Services_ServerToClientStreamClientProtocol {
    private let lock = Lock()
    private var _defaultCallOptions: CallOptions
    private var _interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol?
    public let channel: GRPCChannel
    public var defaultCallOptions: CallOptions {
        get { lock.withLock { self._defaultCallOptions } }
        set { lock.withLockVoid { self._defaultCallOptions = newValue } }
    }

    public var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? {
        get { lock.withLock { self._interceptors } }
        set { lock.withLockVoid { self._interceptors = newValue } }
    }

    /// Creates a client for the services.ServerToClientStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        _defaultCallOptions = defaultCallOptions
        _interceptors = interceptors
    }
}

public struct Services_ServerToClientStreamNIOClient: Services_ServerToClientStreamClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol?

    /// Creates a client for the services.ServerToClientStream service.
    ///
    /// - Parameters:
    ///   - channel: `GRPCChannel` to the service host.
    ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
    ///   - interceptors: A factory providing interceptors for each RPC.
    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ServerToClientStreamAsyncClientProtocol: GRPCClient {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? { get }

    func makeServerStreamCall(
        callOptions: CallOptions?
    ) -> GRPCAsyncBidirectionalStreamingCall<Responses_ClientResponse, Requests_ServerRequest>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ServerToClientStreamAsyncClientProtocol {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ServerToClientStreamClientMetadata.serviceDescriptor
    }

    var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? {
        return nil
    }

    func makeServerStreamCall(
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncBidirectionalStreamingCall<Responses_ClientResponse, Requests_ServerRequest> {
        return makeAsyncBidirectionalStreamingCall(
            path: Services_ServerToClientStreamClientMetadata.Methods.serverStream.path,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeServerStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ServerToClientStreamAsyncClientProtocol {
    func serverStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<Requests_ServerRequest> where RequestStream: Sequence, RequestStream.Element == Responses_ClientResponse {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ServerToClientStreamClientMetadata.Methods.serverStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeServerStreamInterceptors() ?? []
        )
    }

    func serverStream<RequestStream>(
        _ requests: RequestStream,
        callOptions: CallOptions? = nil
    ) -> GRPCAsyncResponseStream<Requests_ServerRequest> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Responses_ClientResponse {
        return performAsyncBidirectionalStreamingCall(
            path: Services_ServerToClientStreamClientMetadata.Methods.serverStream.path,
            requests: requests,
            callOptions: callOptions ?? defaultCallOptions,
            interceptors: interceptors?.makeServerStreamInterceptors() ?? []
        )
    }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Services_ServerToClientStreamAsyncClient: Services_ServerToClientStreamAsyncClientProtocol {
    public var channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol?

    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: Services_ServerToClientStreamClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

public protocol Services_ServerToClientStreamClientInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when invoking 'serverStream'.
    func makeServerStreamInterceptors() -> [ClientInterceptor<Responses_ClientResponse, Requests_ServerRequest>]
}

public enum Services_ServerToClientStreamClientMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ServerToClientStream",
        fullName: "services.ServerToClientStream",
        methods: [
            Services_ServerToClientStreamClientMetadata.Methods.serverStream,
        ]
    )

    public enum Methods {
        public static let serverStream = GRPCMethodDescriptor(
            name: "ServerStream",
            path: "/services.ServerToClientStream/ServerStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Services_ServerToClientStreamProvider: CallHandlerProvider {
    var interceptors: Services_ServerToClientStreamServerInterceptorFactoryProtocol? { get }

    func serverStream(context: StreamingResponseCallContext<Requests_ServerRequest>) -> EventLoopFuture<(StreamEvent<Responses_ClientResponse>) -> Void>
}

public extension Services_ServerToClientStreamProvider {
    var serviceName: Substring {
        return Services_ServerToClientStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    /// Determines, calls and returns the appropriate request handler, depending on the request's method.
    /// Returns nil for methods not handled by this service.
    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ServerStream":
            return BidirectionalStreamingServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<Responses_ClientResponse>(),
                responseSerializer: ProtobufSerializer<Requests_ServerRequest>(),
                interceptors: interceptors?.makeServerStreamInterceptors() ?? [],
                observerFactory: serverStream(context:)
            )

        default:
            return nil
        }
    }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Services_ServerToClientStreamAsyncProvider: CallHandlerProvider, Sendable {
    static var serviceDescriptor: GRPCServiceDescriptor { get }
    var interceptors: Services_ServerToClientStreamServerInterceptorFactoryProtocol? { get }

    func serverStream(
        requestStream: GRPCAsyncRequestStream<Responses_ClientResponse>,
        responseStream: GRPCAsyncResponseStreamWriter<Requests_ServerRequest>,
        context: GRPCAsyncServerCallContext
    ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public extension Services_ServerToClientStreamAsyncProvider {
    static var serviceDescriptor: GRPCServiceDescriptor {
        return Services_ServerToClientStreamServerMetadata.serviceDescriptor
    }

    var serviceName: Substring {
        return Services_ServerToClientStreamServerMetadata.serviceDescriptor.fullName[...]
    }

    var interceptors: Services_ServerToClientStreamServerInterceptorFactoryProtocol? {
        return nil
    }

    func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "ServerStream":
            return GRPCAsyncServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<Responses_ClientResponse>(),
                responseSerializer: ProtobufSerializer<Requests_ServerRequest>(),
                interceptors: interceptors?.makeServerStreamInterceptors() ?? [],
                wrapping: { try await self.serverStream(requestStream: $0, responseStream: $1, context: $2) }
            )

        default:
            return nil
        }
    }
}

public protocol Services_ServerToClientStreamServerInterceptorFactoryProtocol: Sendable {
    /// - Returns: Interceptors to use when handling 'serverStream'.
    ///   Defaults to calling `self.makeInterceptors()`.
    func makeServerStreamInterceptors() -> [ServerInterceptor<Responses_ClientResponse, Requests_ServerRequest>]
}

public enum Services_ServerToClientStreamServerMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "ServerToClientStream",
        fullName: "services.ServerToClientStream",
        methods: [
            Services_ServerToClientStreamServerMetadata.Methods.serverStream,
        ]
    )

    public enum Methods {
        public static let serverStream = GRPCMethodDescriptor(
            name: "ServerStream",
            path: "/services.ServerToClientStream/ServerStream",
            type: GRPCCallType.bidirectionalStreaming
        )
    }
}
